### ISSUE TITLE
some questions about the code

### ISSUE THREAD

**Issue by qdd1234** [ShoufaChen/CycleMLP#3]
Hi, what is the meaning of Underlined code in the picture?
![image](https://user-images.githubusercontent.com/68497831/126786598-edef29f6-d69f-4572-b1a2-055f328b48cf.png)

**Comment by ShoufaChen** [comment]
Hi,

These are learnable weights which represent importance of the corresponding branch.

**Comment by qdd1234** [comment]
> Hi,
> 
> These are learnable weights which represent importance of the corresponding branch.

Thanks! I have another question about code. I find that you use deform_conv2d to achieve the CycleFC. we use deform_conv2d API,  value in offset must be int? or the type of value in offset can be Float?

**Comment by ShoufaChen** [comment]
Currently, we implement the `CycleFC` by hacking `deform_conv2d`, i.e., fixing the offset pattern in our desired format.

As introduced in our paper, the offset should always be `int` value, which is memory-efficient. However, the offsets of the original deform conv are `float` by default.

Furthermore, we have a plan to implement `CycleFC`  with an integrated operator through CUDA instead of haking deforable_conv.

This kernel optimization for Cycle FC has a great potential for faster speed.

**Comment by qdd1234** [comment]
Hi, I have a new question about the code. As shown in the picture, If I delete the Underlined code, the code will raise error which is shown in the second picture, what is the reason? if I do not use register_buffer API, How can I achieve the deform_conv2d?
![image](https://user-images.githubusercontent.com/68497831/127092108-99d80471-c0d5-45f5-beee-0fe920d8c035.png)
![image](https://user-images.githubusercontent.com/68497831/127092154-f2a36a72-aec6-446c-81ab-66589d9a253e.png)

**Comment by ShoufaChen** [comment]
Using `register_buffer` , the `offset` can be moved to gpu when calling `model.cuda()`.

If you don't use it, the `offset` is on the cpu.

**Comment by qdd1234** [comment]
> Using `register_buffer` , the `offset` can be moved to gpu when calling `model.cuda()`.
> 
> If you don't use it, the `offset` is on the cpu.
> 
> Ref: https://discuss.pytorch.org/t/why-model-to-device-wouldnt-put-tensors-on-a-custom-layer-to-the-same-device/17964/8?u=alpha

Thanks! problem is solved!

**Comment by ShoufaChen** [comment]
Closed as no response for a long time.
Feel free to reopen or open a new issue if you have further questions.
